modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/Uranus/issues"
license = "LGPL-3.0"

[[mods]]
modId = "uranus"
version = "${version}"
displayName = "Uranus"
authors = "IAEnvoy"
description = '''
A Library contains animation engine, object helper and so on. Partly based on LLibrary and Citadel.
'''
logoFile = "logo.jpg"

[[dependencies.uranus]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uranus]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uranus]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
