modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/IAFEnvoy/Uranus/issues"
license = "LGPL-3.0"

[[mods]]
modId = "uranus"
version = "${version}"
displayName = "Uranus"
authors = "IAFEnvoy"
description = '''
A Library contains animation engine, object helper and so on. Partly based on LLibrary and Citadel.
'''
logoFile = "logo.jpg"

[[dependencies.uranus]]
modId = "neoforge"
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uranus]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.2,1.20.5)"
ordering = "NONE"
side = "BOTH"

[[dependencies.uranus]]
modId = "architectury"
type = "required"
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "uranus.mixins.json"